name: custom_social_share
description: Flutter Plugin for sharing contents to particular social media app or all.
version: 1.0.2
homepage: https://github.com/keval-devani/custom_social_share

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kd.custom_social_share
        pluginClass: CustomSocialSharePlugin
      ios:
        pluginClass: CustomSocialSharePlugin
